WITH SRC AS (
    SELECT * FROM {{ source('pos', 'menu') }}
),
TRANSFORMED AS (
    SELECT
        COST_OF_GOOD_USD,
        ITEM_CATEGORY,
        ITEM_SUBCATEGORY,
        MENU_ID,
        MENU_ITEM_HEALTH_METRICS_OBJ,
        MENU_ITEM_ID,
        MENU_ITEM_NAME AS ITEM_NAME,
        MENU_TYPE,
        MENU_TYPE_ID,
        SALE_PRICE_USD,
        TRUCK_BRAND_NAME
    FROM SRC
    )

SELECT * FROM TRANSFORMED