WITH SRC AS (
    SELECT * FROM {{ source('pos', 'menu') }}
),
TRANSFORMED AS (
    SELECT
        COST_OF_GOODS_USD,
        UPPER(ITEM_CATEGORY),
        UPPER(ITEM_SUBCATEGORY),
        MENU_ID,
        MENU_ITEM_HEALTH_METRICS_OBJ,
        MENU_ITEM_ID,
        UPPER(MENU_ITEM_NAME) AS ITEM_NAME,
        UPPER(MENU_TYPE),
        MENU_TYPE_ID,
        SALE_PRICE_USD,
        UPPER(TRUCK_BRAND_NAME)
    FROM SRC
    )

SELECT * FROM TRANSFORMED