WITH SRC AS (
    SELECT * FROM {{ source('pos', 'franchise') }}
),
TRANSFORMED AS (
    SELECT
        FRANCHISE_ID,
        UPPER(FIRST_NAME) AS ONWER_FIRST_NAME,
        UPPER(LAST_NAME) AS OWNER_LAST_NAME,
        UPPER(CITY) AS OWNER_CITY,
        UPPER(COUNTRY) AS OWNER_COUNTRY,
        LOWER(E_MAIL) AS EMAIL,
        PHONE_NUMBER
    FROM SRC
    )

SELECT * FROM TRANSFORMED